'use client';import {useEffect,useState} from 'react';import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:5000/api';
async function api(path:string,opts:any={}){const token=typeof window!=='undefined'?localStorage.getItem('token'):'';const r=await fetch(API+path,{...opts,headers:{'content-type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)throw Error((await r.json()).message||'Request failed');return r.json()}
export default function Home(){const [user,setUser]=useState<any>(null);const [stats,setStats]=useState<any>();const [tickets,setTickets]=useState<any[]>([]);const [form,setForm]=useState({subject:'',description:''});const [login,setLogin]=useState({email:'customer1@example.com',password:'Password123!'});const [msg,setMsg]=useState('');
useEffect(()=>{const u=localStorage.getItem('user');if(u){setUser(JSON.parse(u));load(JSON.parse(u))}},[]);
async function load(u:any){try{if(u.role==='admin')setStats(await api('/analytics/dashboard'));setTickets(await api('/tickets'))}catch(e:any){setMsg(e.message)}}
async function signIn(){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify(login)});localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));setUser(d.user);load(d.user)}catch(e:any){setMsg(e.message)}}
async function create(){try{await api('/tickets',{method:'POST',body:JSON.stringify(form)});setForm({subject:'',description:''});setMsg('Ticket created and AI routed successfully');load(user)}catch(e:any){setMsg(e.message)}}
if(!user)return <main className="min-h-screen grid place-items-center p-6"><div className="card w-full max-w-md"><h1 className="text-3xl font-bold mb-2">AI Support Desk</h1><p className="text-slate-500 mb-6">Smart ticketing with AI routing and SLA tracking</p><input className="input mb-3" placeholder="Email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input className="input mb-3" type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button className="btn w-full" onClick={signIn}>Sign in</button><p className="text-red-500 mt-3">{msg}</p></div></main>;
return <main className="min-h-screen p-6 max-w-7xl mx-auto"><header className="flex justify-between items-center mb-6"><div><h1 className="text-3xl font-bold">Support Dashboard</h1><p className="text-slate-500">Welcome, {user.name} · {user.role}</p></div><button className="btn" onClick={()=>{localStorage.clear();location.reload()}}>Logout</button></header>
{stats&&<><div className="grid md:grid-cols-6 gap-4 mb-6">{[['Tickets',stats.total],['Open',stats.open],['Resolved',stats.resolved],['Critical',stats.critical],['SLA Breaches',stats.breached],['CSAT',stats.csat]].map(x=><div className="card" key={x[0]}><div className="text-slate-500">{x[0]}</div><div className="text-2xl font-bold mt-2">{x[1]}</div></div>)}</div><div className="card mb-6"><h2 className="font-bold mb-4">Tickets by Category</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={stats.byCategory.map((x:any)=>({name:x._id,count:x.count}))}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></div></>}
{user.role==='customer'&&<div className="card mb-6"><h2 className="text-xl font-bold mb-4">Create Support Ticket</h2><input className="input mb-3" placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><textarea className="input mb-3 h-28" placeholder="Describe your issue" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="btn" onClick={create}>Create & AI Route Ticket</button><p className="text-green-600 mt-3">{msg}</p></div>}
<div className="card"><h2 className="text-xl font-bold mb-4">Tickets</h2><div className="overflow-auto"><table className="w-full text-left"><thead><tr className="border-b"><th className="p-3">Ticket</th><th>Subject</th><th>Category</th><th>Priority</th><th>Status</th><th>SLA</th></tr></thead><tbody>{tickets.map(t=><tr className="border-b" key={t._id}><td className="p-3">{t.ticketNumber}</td><td>{t.subject}</td><td>{t.category}</td><td>{t.priority}</td><td>{t.status}</td><td>{t.slaStatus||'On Track'}</td></tr>)}</tbody></table></div></div></main>}
